# Generated by Django 2.2.4 on 2019-08-09 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BooksInfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='books',
            new_name='book',
        ),
    ]
